-- This is an autogenerated file representing the INIT migration.
-- It serves as a starting point for the database schema.
-- Note: All tables defined here are expected to already exist in the initial database backup.
-- This migration is used to establish a baseline for tracking future schema changes.
CREATE TABLE IF NOT EXISTS `Articles` (
	`id` int unsigned AUTO_INCREMENT NOT NULL,
	`categoryId` int unsigned NOT NULL,
	`authorId` int unsigned NOT NULL,
	`title` varchar(255) NOT NULL,
	`alias` varchar(255) NOT NULL,
	`image` varchar(255),
	`intro` text NOT NULL,
	`content` mediumtext NOT NULL,
	`status` tinyint NOT NULL,
	`timeToRead` int NOT NULL,
	`metaTitle` varchar(255) NOT NULL,
	`metaDescription` text NOT NULL,
	`publishedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`createdAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updatedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `Articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `IDX_Articles_alias` UNIQUE(`alias`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `Authors` (
	`id` int unsigned AUTO_INCREMENT NOT NULL,
	`alias` varchar(255) NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`position` varchar(255) NOT NULL,
	`photo` varchar(255),
	`bio` text NOT NULL,
	`expertise` json NOT NULL,
	`education` json NOT NULL,
	`socials` json NOT NULL,
	`metaTitle` varchar(255) NOT NULL,
	`metaDescription` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updatedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `Authors_id` PRIMARY KEY(`id`),
	CONSTRAINT `IDX_Authors_alias` UNIQUE(`alias`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `Categories` (
	`id` int unsigned AUTO_INCREMENT NOT NULL,
	`parentId` int unsigned,
	`name` varchar(255) NOT NULL,
	`alias` varchar(255) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updatedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `Categories_id` PRIMARY KEY(`id`),
	CONSTRAINT `IDX_Categories_alias` UNIQUE(`alias`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `Comments` (
	`id` int unsigned AUTO_INCREMENT NOT NULL,
	`articleId` int unsigned NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(254) NOT NULL,
	`content` text NOT NULL,
	`status` tinyint NOT NULL,
	`publishedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`createdAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updatedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `Comments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `Users` (
	`id` int unsigned AUTO_INCREMENT NOT NULL,
	`email` varchar(254) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`role` tinyint NOT NULL,
	`permissions` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	`updatedAt` timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT `Users_id` PRIMARY KEY(`id`),
	CONSTRAINT `IDX_Users_email` UNIQUE(`email`)
);
--> statement-breakpoint
DROP TABLE IF EXISTS `Migrations`;